### ISSUE TITLE
启动游戏之后在启动工具报错

### ISSUE THREAD

**Issue by 0wwp** [SyrieYume/GenshinAutoClick#1]
[Error] Faild to load 'dinput8.dll'!
先启动工具，游戏报错

**Comment by SyrieYume** [comment]
压缩包内的文件都解压出来了吗？`Genshin AutoClick.exe` 和 `dinput8.dll` 处于同一个文件目录下吗

**Comment by 0wwp** [comment]
昨天解决了，好像是因为放在游戏启动器目录下了，换个目录就好了

**Comment by SyrieYume** [comment]
应该是因为，原神运行的时候会检查目录下有没有其它dll
